### PR TITLE
Custom Api endpoint support

### LINKED ISSUE #9: Add custom Susi API endpoint URL support
Add option to add custom Susi API endpoint like local deployments while configuring module.

### PR DESCRIPTION
**Pull request by betterclever**
Fixes #9 : Added support to specify custom API endpoint while using module. By default, http://api.susi.ai is used.

### CODE REVIEW

**Comment by betterclever** [comment]
Do not merge. Needs rebase after #10 and #8 merge

**Comment by mariobehling** [comment]
Please rebase and do the needful.

**Comment by betterclever** [comment]
@DravitLochan @chiragw15 Review please.

**Review by mayank408 — APPROVED** [review]

**Review by chiragw15 — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by amitiwary999 — APPROVED** [review]

**Comment by betterclever** [comment]
@mariobehling Please look into it.

**Pull request merged**
