### PR TITLE
Added audio Parsing in susi

### PR DESCRIPTION
**Pull request by sansyrox**
Susi can now play the test file on the server by `system check`

### CODE REVIEW

**Review by Orbiter — COMMENTED** [review]
Does this require a X11 environment? If yes, please see my comment in https://github.com/fossasia/susi_linux/issues/119#issuecomment-390777634

**Comment by sansyrox** [comment]
@Orbiter , I have changed it accordingly

**Review by akshatnitd — APPROVED** [review]
Looks good!

**Comment by sansyrox** [comment]
@mariobehling @Orbiter  , please have a look

**Comment by sansyrox** [comment]
@mariobehling @Orbiter , can this please be merged. This is causing a blocker to testing the media daemon.

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
