### PR TITLE
Add an example setup.py

### PR DESCRIPTION
**Pull request by felixonmars**
An example setup file to make susi_python a proper PyPI package (as an example of https://github.com/fossasia/susi_linux/issues/319)

### CODE REVIEW

**Comment by felixonmars** [comment]
(Fixes also  #57)

**Review by cweitat — APPROVED** [review]

**Review by sansyrox — APPROVED** [review]

**Review by woshikie — APPROVED** [review]
lgtm

**Comment by hongquan** [comment]
Please not declare to support Python 2.

**Comment by hongquan** [comment]
Please not declare to support MacOSX, Solaris. We don't aim to support and never test on those platform.

**Pull request merged**
