### PR TITLE
Added youtube parsing

### PR DESCRIPTION
**Pull request by sansyrox**
This allows youtube music to be played by using the youtube id

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
:+1:

**Comment by anshumanv** [comment]
Check codacy and fix the code syntax as per it's style guide.

**Review by akshatnitd — COMMENTED** [review]
Codacy is failing

**Comment by sansyrox** [comment]
@akshatnitd , i have fixed those

**Review by akshatnitd — APPROVED** [review]

**Pull request merged**
