### PR TITLE
Added the support for stop action

### PR DESCRIPTION
**Pull request by sansyrox**
I have added support for stop action. 

In the below example, I have forcefully created an invalid query by pressing `ctrl + r`.
And then used the `stop` action to kill the process.

test

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Review by akshatnitd — APPROVED** [review]

**Comment by sansyrox** [comment]
@mariobehling @Orbiter , please have a look

**Review by prateekiiest — APPROVED** [review]

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by sansyrox** [comment]
Done @mariobehling

**Pull request merged**
