### PR TITLE
Adds the Smart speaker to the device section when the user logs in

### PR DESCRIPTION
**Pull request by sansyrox**
Fixes https://github.com/fossasia/susi_linux/issues/156

Fixes https://github.com/fossasia/susi_api_wrapper/issues/48

Now the speaker is shown in the Web App(chat.susi.ai) list when the user signs in

### CODE REVIEW

**Comment by sansyrox** [comment]
@anshumanv @akshatnitd , can you please have a look

**Comment by mariobehling** [comment]
You are giving this issue related to the SUSI Linux repo and state that you solve an issue related to a web client. Which web client? The client at chat.susi.ai? Where is the related issue here?

**Comment by sansyrox** [comment]
@mariobehling , initially I tried to solve the issue through the susi_linux repo and hence opened an issue in the susi_linux repo but since now has to be resolved through susi_api_wrapper , I have opened an issue here

**Comment by mariobehling** [comment]
Ok, got it. Merging your other PR created a conflict again. Please help to resolve it.

**Pull request merged**
